# -*- coding: utf-8 -*-
"""news_article_summarizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ol5zA5Nozs3FJWS9lszQzArO7f6mQmcN
"""

# ============================================================
# MULTILINGUAL AI NEWS ARTICLE SUMMARIZER
# GOOGLE COLAB COMPLETE WEBSITE PROJECT
# Supports:
# English, Hindi, Kannada, Tamil, Telugu,
# Malayalam, Bengali, Marathi, Gujarati, Punjabi
# ============================================================

# ============================================================
# STEP 1 — INSTALL REQUIRED LIBRARIES
# ============================================================

!pip install transformers -q
!pip install sentencepiece -q
!pip install torch -q
!pip install gradio -q
!pip install langdetect -q
!pip install newspaper3k -q
!pip install nltk -q
!pip install PyPDF2 -q
!pip install python-docx -q
!pip install lxml_html_clean -q

# ============================================================
# STEP 2 — IMPORT LIBRARIES
# ============================================================

import gradio as gr
import nltk
import torch
import re
import PyPDF2
import docx

from newspaper import Article
from langdetect import detect
from transformers import pipeline
from nltk.tokenize import sent_tokenize

# Download tokenizer
nltk.download('punkt')
nltk.download('punkt_tab')

# ============================================================
# STEP 3 — LOAD MULTILINGUAL SUMMARIZATION MODEL
# ============================================================

from transformers import pipeline

print("Loading AI Model... Please wait...")

summarizer = pipeline(
    task="text-generation",
    model="google/flan-t5-base",
    device=0 if torch.cuda.is_available() else -1
)

print("Model Loaded Successfully!")

# STEP 4 — LANGUAGE DETECTION
# ============================================================

language_names = {
    "en": "English",
    "hi": "Hindi",
    "kn": "Kannada",
    "ta": "Tamil",
    "te": "Telugu",
    "ml": "Malayalam",
    "bn": "Bengali",
    "mr": "Marathi",
    "gu": "Gujarati",
    "pa": "Punjabi"
}

def detect_language(text):

    try:

        lang = detect(text)

        return language_names.get(lang, lang)

    except:

        return "Unknown"

# STEP 5 — CLEAN TEXT
# ============================================================

def clean_text(text):

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

# STEP 6 — SPLIT LONG ARTICLES INTO CHUNKS
# ============================================================

def split_into_chunks(text, chunk_size=1000):

    sentences = sent_tokenize(text)

    chunks = []

    current_chunk = ""

    for sentence in sentences:

        if len(current_chunk) + len(sentence) <= chunk_size:

            current_chunk += " " + sentence

        else:

            chunks.append(current_chunk)

            current_chunk = sentence

    if current_chunk:

        chunks.append(current_chunk)

    return chunks

# ============================================================
# STEP 7 — MAIN SUMMARIZATION FUNCTION
# ============================================================

def summarize_article(text):

    try:

        text = clean_text(text)

        if len(text) < 100:

            return """
Please enter a longer news article.
Minimum 100 characters required.
"""

        detected_language = detect_language(text)

        chunks = split_into_chunks(text)

        summaries = []

        for chunk in chunks:

            summary = summarizer(
                chunk,
                max_length=120,
                min_length=40,
                do_sample=False
            )

            summaries.append(
                summary[0]['generated_text']
            )

        final_summary = " ".join(summaries)

        result = f"""
==============================
DETECTED LANGUAGE
==============================

{detected_language}

==============================
GENERATED SUMMARY
==============================

{final_summary}
"""

        return result

    except Exception as e:

        return f"Error: {str(e)}"

# STEP 8 — SUMMARIZE ARTICLE FROM URL
# ============================================================

def summarize_news_url(url):

    try:

        article = Article(url)

        article.download()

        article.parse()

        text = article.text

        return summarize_article(text)

    except Exception as e:

        return f"URL Processing Error: {str(e)}"

# STEP 9 — TXT FILE READER
# ============================================================

def read_txt(file):

    with open(file.name, "r", encoding="utf-8") as f:

        text = f.read()

    return text

# STEP 10 — PDF FILE READER
# ============================================================

def read_pdf(file):

    text = ""

    pdf_reader = PyPDF2.PdfReader(file)

    for page in pdf_reader.pages:

        extracted = page.extract_text()

        if extracted:

            text += extracted

    return text

# STEP 11 — DOCX FILE READER
# ============================================================

def read_docx(file):

    document = docx.Document(file)

    text = ""

    for para in document.paragraphs:

        text += para.text + "\n"

    return text

##STEP 12 — UNIVERSAL FILE LOADER
# ============================================================

def load_article_file(file):

    try:

        filename = file.name.lower()

        if filename.endswith(".txt"):

            return read_txt(file)

        elif filename.endswith(".pdf"):

            return read_pdf(file)

        elif filename.endswith(".docx"):

            return read_docx(file)

        else:

            return "Unsupported file format"

    except Exception as e:

        return f"File Loading Error: {str(e)}"

##STEP 13 — SUMMARIZE UPLOADED FILE
# ============================================================

def summarize_uploaded_file(file):

    text = load_article_file(file)

    return summarize_article(text)

# ============================================================
# STEP 14 — CREATE MODERN AI WEBSITE USING GRADIO
# ============================================================

with gr.Blocks(
    theme=gr.themes.Soft(
        primary_hue="blue",
        secondary_hue="violet"
    ),
    title="AI News Summarizer"
) as app:

    # ========================================================
    # HERO SECTION
    # ========================================================

    gr.HTML("""

    <div style="
        text-align:center;
        padding:40px;
        border-radius:25px;
        background:linear-gradient(to right,#2563eb,#7c3aed);
        color:white;
        margin-bottom:25px;
        box-shadow:0 4px 20px rgba(0,0,0,0.15);
    ">

    <h1 style="
        font-size:48px;
        margin-bottom:10px;
    ">
    📰 AI News Summarizer
    </h1>

    <p style="
        font-size:20px;
        opacity:0.95;
    ">
    Summarize Long News Articles Using AI & NLP
    </p>

    </div>

    """)

    # ========================================================
    # FEATURE CARDS
    # ========================================================

    gr.HTML("""

    <div style="
        display:flex;
        justify-content:center;
        gap:20px;
        flex-wrap:wrap;
        margin-bottom:25px;
    ">

    <div style="
        background:#eff6ff;
        padding:20px;
        border-radius:18px;
        width:230px;
        text-align:center;
        box-shadow:0 2px 12px rgba(0,0,0,0.08);
    ">
    <h3>🌍 Multilingual</h3>
    <p>Supports Indian Languages + English</p>
    </div>

    <div style="
        background:#f5f3ff;
        padding:20px;
        border-radius:18px;
        width:230px;
        text-align:center;
        box-shadow:0 2px 12px rgba(0,0,0,0.08);
    ">
    <h3>🤖 AI Powered</h3>
    <p>Transformer-based NLP Summarization</p>
    </div>

    <div style="
        background:#ecfeff;
        padding:20px;
        border-radius:18px;
        width:230px;
        text-align:center;
        box-shadow:0 2px 12px rgba(0,0,0,0.08);
    ">
    <h3>📂 File Upload</h3>
    <p>Upload PDF, DOCX & TXT Files</p>
    </div>

    </div>

    """)

    # ========================================================
    # TAB 1 — PASTE ARTICLE
    # ========================================================

    with gr.Tab("📝 Paste Article"):

        input_text = gr.Textbox(
            lines=20,
            placeholder="Paste long news article here...",
            label="News Article",
            elem_classes="textbox"
        )

        summarize_btn = gr.Button(
            "Generate Summary",
            variant="primary"
        )

        output_summary = gr.Textbox(
            lines=18,
            label="AI Generated Summary"
        )

        summarize_btn.click(
            fn=summarize_article,
            inputs=input_text,
            outputs=output_summary
        )

    # ========================================================
    # TAB 2 — URL SUMMARIZATION
    # ========================================================

    with gr.Tab("🌐 Summarize From URL"):

        input_url = gr.Textbox(
            label="Paste News URL",
            placeholder="https://example.com/news-article"
        )

        url_btn = gr.Button(
            "Summarize URL",
            variant="primary"
        )

        url_output = gr.Textbox(
            lines=18,
            label="AI Generated Summary"
        )

        url_btn.click(
            fn=summarize_news_url,
            inputs=input_url,
            outputs=url_output
        )

    # ========================================================
    # TAB 3 — FILE UPLOAD
    # ========================================================

    with gr.Tab("📂 Upload Article File"):

        file_input = gr.File(
            label="Upload PDF / TXT / DOCX File"
        )

        file_btn = gr.Button(
            "Summarize File",
            variant="primary"
        )

        file_output = gr.Textbox(
            lines=18,
            label="AI Generated Summary"
        )

        file_btn.click(
            fn=summarize_uploaded_file,
            inputs=file_input,
            outputs=file_output
        )

    # ========================================================
    # FOOTER
    # ========================================================

    gr.HTML("""

    <div style="
        text-align:center;
        margin-top:30px;
        padding:20px;
        color:gray;
        font-size:15px;
    ">

    🚀 Powered by AI • NLP • Transformers • Gradio

    </div>

    """)

##============================================================
# STEP 15 — LAUNCH WEBSITE
# ============================================================

app.launch(
    share=True,
    debug=True
)